name: Pytest program

on: push

jobs:

  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout changes
        uses: actions/checkout@v3    
    
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip    
          pip install flake8 pytest

      - name: Linting project with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true

      - name: Test project
        run: |     
          pytest test_try.py --doctest-modules --junitxml=junit/test-results.xml
