name: Pytest program

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout changes
      - uses: actions/checkout@v3      
        run: echo This is a demo start workflow
