name: Python pytest
on: push

jobs:
  test:

    runs-on: ubuntu-latest    

    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Testing the project using pytest
        run: |
          pytest
