name: Pytest program

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3    
      - name: checkout changes
        run: echo This is a demo start workflow
        
      - uses: actions/setup-python@v4
      - name: Set up Python 3.11
      
