# .github/workflows/pytest.yaml
name: Python pytest
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest    
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
        
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: Linting project with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          continue-on-error: true
          
      - name: Testing the project using pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml
