name: Pytest program

on: push

jobs:

  checkout-job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3    
      - name: checkout changes
        run: echo This is a demo start workflow
        
  setup-python:
    runs-on: ubuntu-latest     
    needs: ["checkout-job"]    
    steps:      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 
          
  install-dependencies:
    runs-on: ubuntu-latest     
    needs: ["setup-python"]
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
  
  test-project:
    runs-on: ubuntu-latest     
    needs: ["install-dependencies"]
    steps:
      - name: Test project
        run: |
          pip install pytest
          pip install pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
