name: Pytest program

on: push

jobs:

  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout changes
        uses: actions/checkout@v3    
    
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip    
          pip install pytest pytest-cov

      - name: Test project
        run: |     
          pytest tests/base --cov=spock --cov-config=.coveragerc --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov-report=xml --cov-report=html
          
