name: Pytest program

on: push

jobs:

  checkout-job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3    
      - name: checkout changes
        run: echo This is a demo start workflow
    
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip    
          pip install pytest
          pip install pytest-cov
  
      - name: Test project
        run: |     
          pytest test_try.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
